### ISSUE TITLE
Relation to pavao?

### ISSUE THREAD

**Issue by moranbw** [veeso/remotefs-rs-smb#1]
So is it correct that this library depends on [pavão](https://github.com/veeso/pavao)?

I'm developing primarily for Windows at the moment, so it seems like this is the crate to use for connecting to SMB shares, as pavão does not appear to support Windows?

Thanks

**Comment by veeso** [comment]
Hi, this library relies on pavao for MacOS/Linux only, otherwise it uses the native windows api.

If you want you can just connect to the SMB share following this guide: <https://blog.veeso.dev/blog/how-to-access-an-smb-share-with-rust-on-windows/>
